
(async () => {
  const check = (value, message) => { if (!value) throw new Error(message); };
  try {
    localStorage.clear();
    const text = ("# Memory source\n\n" + "Learning creates lasting impressions. ".repeat(110)).trim();
    await importTextFile({target:{files:[new File([text],"memory.md",{type:"text/markdown"})],value:""}});
    check(loadArticles().length === 1, "file import");
    const parentId = currentArticleId;
    splitCurrentArticle();
    const firstParts = loadArticles().filter(a=>a.parentArticleId===parentId);
    check(firstParts.length > 1, "sections created");
    check(firstParts.map(a=>a.content).join("") === text, "lossless sections");
    splitCurrentArticle();
    check(loadArticles().length === firstParts.length+1, "idempotent splitting");
    loadArticleIntoTrainer(firstParts[0]);
    sourceText.value = "An edited child section";
    saveCurrentArticle();
    check(loadArticles().find(a=>a.id===parentId).content===text, "child must not overwrite parent");
    check(loadArticles().find(a=>a.id===firstParts[0].id).revisions[0].content===firstParts[0].content, "child version");
    loadArticleIntoTrainer(loadArticles().find(a=>a.id===parentId));
    sourceText.value = text + "\nNew content";
    saveCurrentArticle();
    check(loadArticles().find(a=>a.id===parentId).contentVersion===2, "parent version");
    loadArticleIntoTrainer(loadArticles().find(a=>a.id===firstParts[0].id));
    check(document.querySelector("#contentVersions").textContent.includes(text), "source snapshot visible");
    impressionInput.value="Find this impression";
    saveCurrentArticle();
    articleSearchInput.value="Find this impression";
    renderArticleLibrary();
    check(articleLibraryList.children.length===1, "impression search");
    const backup={schemaVersion:2,app:"Memorizer",articles:loadArticles(),sessions:[]};
    localStorage.clear();
    await importTrainingData({target:{files:[{text:async()=>JSON.stringify(backup)}]}});
    const restored=loadArticles().find(a=>a.id===firstParts[0].id);
    check(restored.parentSnapshot===text && restored.revisions.length===1, "backup sections and history");
    loadArticleIntoTrainer(restored);
    recallMode.value="threePoints";
    expectedPointsInput.value="First expected\nSecond expected";
    startReading();
    check(!activeRound, "reject incomplete expected points");
    expectedPointsInput.value="First expected\nSecond expected\nThird expected";
    saveArticleButton.click();
    const trainingId=currentArticleId;
    loadArticleIntoTrainer(loadArticles().find(a=>a.id===trainingId));
    check(recallMode.value==="threePoints" && expectedPointsInput.value.includes("Third expected"), "reload expected points and mode");
    for(let i=0;i<14;i++) {
      startReadingButton.click();
      hideNowButton.click();
      check(getComputedStyle(document.querySelector(".source-panel")).display==="none", "hide source and expected points");
      check(getComputedStyle(articleLibraryList.closest(".history-panel")).display==="none", "hide previous answers");
      check(document.querySelector("#expectedPreview").textContent==="", "no comparison before submission");
      check(hintButton.disabled && structureButton.disabled, "no source hints in three-point mode");
      document.querySelector("#recallPoint1").value="My first point " + i;
      document.querySelector("#recallPoint2").value="My second point";
      document.querySelector("#recallPoint3").value="My third point";
      finishRecallButton.click();
      check(document.querySelector("#expectedPreview").textContent.includes("First expected"), "compare after submission");
      check(document.querySelector("#recallPreview").textContent.includes("My first point " + i), "submitted recall");
      scoreSlider.value="5"; confidenceSlider.value="5";
      missingText.value="Missed detail " + i;
      saveSessionButton.click(); saveSessionButton.click();
      const trained=loadArticles().find(a=>a.id===trainingId);
      check(trained.attempts.length===i+1, "save once per round");
      check(trained.status===(i<2 ? "learning" : "mastered"), "repeated performance mastery");
      newRoundButton.click();
    }
    let trained=loadArticles().find(a=>a.id===trainingId);
    check(loadMemoryHistory().length===14, "retain more than twelve sessions");
    expectedPointsInput.value="Changed expected\nSecond expected\nThird expected";
    saveArticleButton.click();
    trained=loadArticles().find(a=>a.id===trainingId);
    check(trained.status==="newReview" && trained.attempts[0].expectedPoints[0]==="First expected", "edit preserves past expected snapshot and resets progress");
    articleSearchInput.value=""; renderArticleLibrary();
    const historyCard=[...articleLibraryList.children].find(card=>card.querySelector(".attempt-history summary")?.textContent.includes("(14)"));
    check(historyCard && historyCard.querySelectorAll(".attempt-history .history-item").length===14, "complete article history");
    check(historyCard.textContent.includes("My first point 0") && historyCard.textContent.includes("Missed detail 13"), "full oldest and newest responses");
    const trainingBackup={schemaVersion:2,app:"Memorizer",articles:loadArticles(),sessions:loadMemoryHistory()};
    localStorage.clear();
    await importTrainingData({target:{files:[{text:async()=>JSON.stringify(trainingBackup)}]}});
    check(loadArticles().find(a=>a.id===trainingId).attempts.length===14 && loadMemoryHistory().length===14, "training backup roundtrip");
    loadArticleIntoTrainer(loadArticles().find(a=>a.id===trainingId));
    recallMode.value="free";
    startReadingButton.click(); hideNowButton.click();
    recallText.value="Legacy free recall still works";
    finishRecallButton.click(); scoreSlider.value="1"; saveSessionButton.click();
    check(loadArticles().find(a=>a.id===trainingId).attempts[0].recall===recallText.value, "free recall preserved");
    newRoundButton.click();
    currentLanguage="en"; applyLanguage();
    check(document.querySelector("#splitArticleButton").textContent==="Split for practice","English");
    document.body.innerHTML="<pre id='result'>PASS: real DOM import, lossless/idempotent sections, parent isolation, versions, snapshots, impression search, backup round trip, bilingual UI, three-point recall, delayed comparison, complete history, repeated-performance scheduling, training backup</pre>";
  } catch (error) {
    document.body.innerHTML="<pre id='result'></pre>";
    document.querySelector("#result").textContent="FAIL: "+error.stack;
  }
})();
